#-------------------------------
# General Site Settings

title: Sarah Aslanifar
description: Write to clear my brain!
baseurl: ""
url: "http://sarahaslanifar.com"


#-------------------------------
# About Section
author-name:   Sarah Aslanifar
author-avatar: me_avatar.png


#-------------------------------
# Contact links
testedminds: http://testedminds.com
github: https://github.com/saslani
linkedin: http://linkedin.in/in/felfeli
twitter: https://twitter.com/testedminds


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: saslani


#-------------------------------
# Google Analytics
google-analytics: UA-155767940-1


#-------------------------------
# Build settings
markdown: kramdown
permalink: ":title/"
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
